name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.8.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  geolocator: ^10.0.1
  getwidget: ^4.0.0
  google_maps: ^6.3.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  location: ^5.0.3
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
