// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKDBGN_PxGh_eXHAM7y2FLBgcvTlw3gXs',
    appId: '1:760549182014:web:8102482af91da300395f6f',
    messagingSenderId: '760549182014',
    projectId: 'donate-a-bite-287fb',
    authDomain: 'donate-a-bite-287fb.firebaseapp.com',
    storageBucket: 'donate-a-bite-287fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlvgjHq8U93dnpaov1RXxmiuLvcgh9V0',
    appId: '1:760549182014:android:14251d912f0e7cdc395f6f',
    messagingSenderId: '760549182014',
    projectId: 'donate-a-bite-287fb',
    storageBucket: 'donate-a-bite-287fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD62dq_WhL4NTkMeYc4F6FISkPDFt-CgE',
    appId: '1:760549182014:ios:934487326f2102c8395f6f',
    messagingSenderId: '760549182014',
    projectId: 'donate-a-bite-287fb',
    storageBucket: 'donate-a-bite-287fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD62dq_WhL4NTkMeYc4F6FISkPDFt-CgE',
    appId: '1:760549182014:ios:1ada24aaa9fc85ae395f6f',
    messagingSenderId: '760549182014',
    projectId: 'donate-a-bite-287fb',
    storageBucket: 'donate-a-bite-287fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
